/**
 * Solarch CLI — Canonical Error Codes
 *
 * Defines machine-readable, actionable error codes across all CLI subsystems.
 */

export const SolarchErrorCode = {
  // Authentication (Phase 2)
  AUTH_REQUIRED: 'SOLARCH_AUTH_REQUIRED',
  AUTH_EXPIRED: 'SOLARCH_AUTH_EXPIRED',
  AUTH_INVALID_TOKEN: 'SOLARCH_AUTH_INVALID_TOKEN',

  // Project & Manifest (Phase 1, 4)
  PROJECT_NOT_FOUND: 'SOLARCH_PROJECT_NOT_FOUND',
  PROJECT_ALREADY_EXISTS: 'SOLARCH_PROJECT_ALREADY_EXISTS',
  CONFIG_INVALID: 'SOLARCH_CONFIG_INVALID',
  CONFIG_CONFLICT: 'SOLARCH_CONFIG_CONFLICT',

  // SDK & Package Management (Phase 3)
  SDK_NOT_FOUND: 'SOLARCH_SDK_NOT_FOUND',
  PACKAGE_MANAGER_FAILED: 'SOLARCH_PACKAGE_MANAGER_FAILED',

  // Plugins (Phase 5)
  PLUGIN_NOT_FOUND: 'SOLARCH_PLUGIN_NOT_FOUND',
  PLUGIN_INCOMPATIBLE: 'SOLARCH_PLUGIN_INCOMPATIBLE',

  // Database (Phase 6)
  DATABASE_CONNECTION_FAILED: 'SOLARCH_DATABASE_CONNECTION_FAILED',
  DATABASE_MIGRATION_FAILED: 'SOLARCH_DATABASE_MIGRATION_FAILED',
  DATABASE_TOPOLOGY_MISMATCH: 'SOLARCH_DATABASE_TOPOLOGY_MISMATCH',

  // Deployment (Phase 7)
  DEPLOYMENT_PACKAGING_FAILED: 'SOLARCH_DEPLOYMENT_PACKAGING_FAILED',
  DEPLOYMENT_SECRET_LEAK: 'SOLARCH_DEPLOYMENT_SECRET_LEAK',
  DEPLOYMENT_FAILED: 'SOLARCH_DEPLOYMENT_FAILED',
  DEPLOYMENT_HEALTH_FAILED: 'SOLARCH_DEPLOYMENT_HEALTH_FAILED',

  // Service & Control Plane (Phase 9)
  SERVICE_NOT_FOUND: 'SOLARCH_SERVICE_NOT_FOUND',
  SERVICE_CIRCUIT_BROKEN: 'SOLARCH_SERVICE_CIRCUIT_BROKEN',
  SERVICE_RECOVERY_LOCKED: 'SOLARCH_SERVICE_RECOVERY_LOCKED',

  // MCP & Governance (Phase 10)
  MCP_TOOL_NOT_FOUND: 'SOLARCH_MCP_TOOL_NOT_FOUND',
  MCP_APPROVAL_REQUIRED: 'SOLARCH_MCP_APPROVAL_REQUIRED',
  MCP_PERMISSION_DENIED: 'SOLARCH_MCP_PERMISSION_DENIED',

  // Generic
  INTERNAL_ERROR: 'SOLARCH_INTERNAL_ERROR',
  VALIDATION_ERROR: 'SOLARCH_VALIDATION_ERROR',
} as const

export type SolarchErrorCodeType = (typeof SolarchErrorCode)[keyof typeof SolarchErrorCode]
